[package]
name = "hlvm"
version = "0.3.0"
authors = ["adam"]
edition = "2018"

[dependencies]
bigdecimal = "0.0.15"

[lib]
name = "hlvm"
path = "src/lib.rs"

[[bin]]
name = "hlvm"
path = "src/bin.rs"


[profile.release]
opt-level = 3
